version: '3'
services:
  schemaspy:
    image: schemaspy/schemaspy
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/config:/config
    container_name: "schemaspy_local"
    command: ["-configFile", "/config/schemaspy.properties"]